# Site settings
title: "Cédric Cherdel"

prenom: Cedric

nom: CHERDEL

subtitle-danse: Chorégraphe
subtitle-massage: Masseur Thaï

dossier: creations

email: webmaster@cedriccherdel.com

# description: > # this means to ignore newlines until "baseurl:"
#     Write an awesome description for your new site here. You can edit this
#     line in _config.yml. It will appear in your document head meta (for
#     Google search results) and in your feed.xml site description.

baseurl: "" # the subpath of your site, e.g. /blog/

url: "http://www.cedriccherdel.com" # the base hostname & protocol for your site

#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown

timezone: Europe/Paris

collections:
    creations:
        label: 2_creations
        permalink: /creations/:path/
        output: true

encoding: utf-8

markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext: "textile,txtl,tl"

exclude:
    - cedriccherdel.com.sublime-project
    - feed.xml
    - README.md

gems:
    - jekyll-textile-converter
